#solicitud de ingreso de informacion
print()
print("Bienvenidos a continuacion favor ingresar los datos solicitados")
print()
nombre = input("Por favor ingrese su nombre:")
apellido = input("Por favor ingrese su apellido:")
carrera = input("Por favor ingrese su carrera:")
codigo_seccion =  input("por favor ingrese su codigo-seccion:")
sede = input("por favor ingresar sede en la que estudia:")
print()
print("Buenas tardes " + nombre, apellido + " estas en la carrera de " + carrera + "  y su seccion es la " + codigo_seccion + " y estudias en la sede " + sede + " INACAP.")
